# It's needed for annotations
mdn:
    resource: @MDNListBundle/Controller/
    type:     annotation
    
    
# I'm not using it at the moment. Apparently annotations are the way to go
#mdn_list_homepage:
#    path:     /
#    defaults: { _controller: MDNListBundle:Default:index }

